Repository TTG-Club/ttg-club-frontend, pull requests merged in 2023-11, with the labels that each got.

#217 [TTG-3] Создать Токенатор
  public/img/dark/bg-token.webp
  public/img/light/bg-token.webp
  public/img/token/token-bg.webp
  public/img/token/token-border.webp
  src/assets/icons/svg/zoom/in.svg
  src/assets/icons/svg/zoom/out.svg
  src/assets/styles/theme.scss
  src/core/router/routes.ts
  src/pages/Tools/Tokenator/TokenDetails.vue
  src/pages/Tools/Tokenator/TokenStamp.vue
  src/pages/Tools/Tokenator/TokenView.vue
  src/pages/Tools/Tokenator/composable/index.ts
  src/shared/ui/kit/button/UiButton.d.ts
  src/shared/ui/kit/button/UiButton.vue
  src/shared/ui/kit/slider/UiRangeSlider.vue
  src/shared/ui/kit/slider/UiSlider.vue
Labels: фича

#224 update scss, no avatar img
  public/img/no-img.png
  public/img/no-img.webp
  src/shared/ui/kit/UiEasyLightbox.vue
Labels: улучшение

#225 fix: text shown badly in light mode
  src/pages/Inventory/MagicItems/MagicItemLink.vue
Labels: bug

#226 fix: cursor moves to the end from any point if start typing
  src/pages/Search/SearchModal.vue
Labels: bug

#227 fix: adaptive styles for tokenator
  src/pages/Tools/Tokenator/TokenDetails.vue
Labels: bug

#228 fix: show errors in tokenator
  src/pages/Tools/Tokenator/composable/index.ts
Labels: bug

#229 fix: tokenator cursor, size, mobile styles
  src/pages/Tools/Tokenator/TokenStamp.vue
  src/pages/Tools/Tokenator/TokenView.vue
Labels: bug

#230 fix: add center axis button, add reflect button, add drop zone, fix reflected image dragging
  src/assets/icons/svg/centerAxis.svg
  src/assets/icons/svg/reflect.svg
  src/pages/Tools/Tokenator/TokenDetails.vue
  src/pages/Tools/Tokenator/TokenStamp.vue
  src/pages/Tools/Tokenator/composable/index.ts
Labels: bug, улучшение

#222 fix main bg page
  public/img/dark/bg-main-ng.webp
  public/img/light/bg-main-ng.webp
  src/assets/styles/theme.scss
Labels: wontfix

#233 fix stats
  src/assets/styles/main.scss
Labels: bug

#234 Release
  package-lock.json
  package.json
  public/img/bg_token_library.webp
  public/img/dark/bg-main-ng.webp
  public/img/dark/bg-token.webp
  public/img/light/bg-main-ng.webp
  public/img/light/bg-token.webp
  public/img/no-img.png
  public/img/no-img.webp
  public/img/token/token-bg.webp
  public/img/token/token-border.webp
  src/assets/icons/svg/centerAxis.svg
  src/assets/icons/svg/reflect.svg
  src/assets/icons/svg/zoom/in.svg
  src/assets/icons/svg/zoom/out.svg
  src/assets/styles/_typography.scss
  src/assets/styles/main.scss
  src/assets/styles/theme.scss
  src/core/router/routes.ts
  src/features/SectionHeader.vue
  src/pages/Character/Classes/ClassDetail.vue
  src/pages/IndexView.vue
  src/pages/Inventory/MagicItems/MagicItemLink.vue
  src/pages/Search/SearchModal.vue
  src/pages/Tools/Tokenator/TokenDetails.vue
  src/pages/Tools/Tokenator/TokenStamp.vue
  src/pages/Tools/Tokenator/TokenView.vue
  src/pages/Tools/Tokenator/composable/index.ts
  src/shared/helpers/isAppleDevice.ts
  src/shared/ui/icons/SvgIcon.vue
  src/shared/ui/kit/UiEasyLightbox.vue
  src/shared/ui/kit/button/UiButton.d.ts
  src/shared/ui/kit/button/UiButton.vue
  src/shared/ui/kit/slider/UiRangeSlider.vue
  src/shared/ui/kit/slider/UiSlider.vue
  tsconfig.json
Labels: release
