Repository TTG-Club/ttg-club-frontend, pull requests merged in 2023-10, with the labels that each got.

#199 feat: add export to foundry for spells
  src/pages/Character/Spells/SpellDetail.vue
Labels: фича

#192 feat: bookmark remove confirmation
  src/assets/styles/_typography.scss
  src/features/DetailTopBar.vue
  src/features/SectionHeader.vue
  src/features/bookmarks/components/BookmarkRemoveConfirmationModal.vue
  src/features/bookmarks/components/CustomBookmarks/CustomBookmarkCategory.vue
  src/features/bookmarks/components/CustomBookmarks/CustomBookmarkGroup.vue
  src/features/bookmarks/components/DefaultBookmarks.vue
  src/features/bookmarks/store/CustomBookmarksStore.ts
  src/features/bookmarks/store/DefaultBookmarkStore.ts
  src/features/bookmarks/utils/index.ts
  src/features/filter/FilterItem/FilterItem.module.scss
  src/features/filter/ListFilter.vue
  src/features/menu/NavBar.vue
  src/features/menu/NavMenu.vue
  src/features/menu/NavPopover.vue
  src/features/menu/NavProfile.vue
  src/features/youtube/components/YoutubeAddVideo.vue
  src/features/youtube/components/YoutubeBlock.vue
  src/features/youtube/components/YoutubeEditVideo.vue
  src/features/youtube/components/YoutubePlayer.vue
  src/features/youtube/views/YoutubeView.vue
  src/layouts/ContentLayout.vue
  src/layouts/PageLayout.vue
  src/layouts/TabLayout.vue
  src/pages/Character/Classes/ClassDetail.vue
  src/pages/Character/Classes/ClassesView.vue
  src/pages/Character/Races/RaceLink.vue
  src/pages/Character/Races/RacesView.vue
  src/pages/Character/Spells/SpellLink.vue
  src/pages/Search/SearchLink.vue
  src/pages/Search/SearchModal.vue
  src/pages/Tools/AbilityCalc/AbilityRaces/AbilityRaces.vue
  src/pages/Tools/AbilityCalc/AbilityTable.vue
  src/pages/Workshop/Screens/ScreenLink.vue
  src/pages/Workshop/Screens/ScreensGroup.vue
  src/pages/Workshop/Screens/ScreensView.vue
  src/shared/ui/DiceRoller.vue
  src/shared/ui/SocialLinks.vue
  src/shared/ui/icons/IconToastClose.vue
  src/shared/ui/kit/UiCheckbox.vue
  src/shared/ui/kit/UiEasyLightbox.vue
  src/shared/ui/kit/UiInput.vue
  src/shared/ui/kit/UiPaginate.vue
  src/shared/ui/kit/UiSelect.vue
  src/shared/ui/kit/UiSwitch.vue
  src/shared/ui/kit/button/UiButton.vue
  src/shared/ui/kit/button/UiSocialButton.vue
  src/shared/ui/modals/AuthModal.vue
  src/shared/ui/modals/BaseModal.vue
Labels: фича

#200 feat: auto theme detector
  .github/workflows/lint.yml
  .github/workflows/type-check.yml
  src/assets/styles/_print.scss
  src/assets/styles/_typography.scss
  src/assets/styles/theme.scss
  src/assets/styles/variables/colors.scss
  src/assets/styles/variables/mixins.scss
  src/core/App.vue
  src/features/MenuThemeSwitcher.vue
  src/features/SectionHeader.vue
  src/features/bookmarks/store/CustomBookmarksStore.ts
  src/features/menu/NavPopover.vue
  src/features/menu/NavProfile.vue
  src/shared/constants/UI.ts
  src/shared/stores/UIStore.ts
  src/shared/ui/kit/button/UiButton.vue
Labels: фича

#205 chore: update pagination naming
  src/features/youtube/api/index.ts
  src/features/youtube/components/YoutubeBlock.vue
  src/features/youtube/composition/useYoutube.ts
  src/features/youtube/views/YoutubeView.vue
  src/pages/Character/Backgrounds/BackgroundsView.vue
  src/pages/Character/Classes/ClassesView.vue
  src/pages/Character/Races/RacesView.vue
  src/pages/Character/Traits/TraitsView.vue
  src/pages/Inventory/Armors/ArmorsView.vue
  src/pages/Inventory/Weapons/WeaponsView.vue
  src/pages/Search/SearchModal.vue
  src/pages/Search/SearchView.vue
  src/pages/Tools/AbilityCalc/AbilityRaces/AbilityRaces.vue
  src/shared/compositions/usePagination.ts
  src/shared/constants/index.ts
  src/shared/types/BaseApiFields.d.ts
  src/shared/types/Search/Search.d.ts
Labels: улучшение

#209 feat: foundry version dropdown for spells and bestiary
  src/features/SectionHeader.vue
  src/pages/Character/Spells/SpellDetail.vue
  src/pages/Workshop/Bestiary/CreatureDetail.vue
  src/shared/types/Character/Spells.d.ts
Labels: фича

#211 fix: update api path
  src/pages/Character/Spells/SpellDetail.vue
  src/pages/Workshop/Bestiary/CreatureDetail.vue
Labels: bug

#208 fix: multiple race highlightning, hide collapse item if subraces list is empty
  src/pages/Character/Races/RaceLink.vue
Labels: bug

#214 hotfix: show error message if spell or creature not yet ready for export
  src/features/SectionHeader.vue
  src/pages/Character/Spells/SpellDetail.vue
  src/pages/Workshop/Bestiary/CreatureDetail.vue
Labels: bug

#215 hotfix: update download for spell and bestiary with toast message
  src/pages/Character/Spells/SpellDetail.vue
  src/pages/Workshop/Bestiary/CreatureDetail.vue
Labels: bug

#216 Dev
  src/features/SectionHeader.vue
  src/pages/Character/Spells/SpellDetail.vue
  src/pages/Workshop/Bestiary/CreatureDetail.vue
Labels: bug, release

#218 fix title
  src/assets/styles/_typography.scss
  src/features/SectionHeader.vue
Labels: улучшение

#223 feat: update main page
  public/img/bg_token_library.webp
  src/assets/styles/main.scss
  src/pages/IndexView.vue
Labels: улучшение
