Repository TTG-Club/ttg-club-frontend, pull requests merged in 2023-06, with the labels that each got.

#141 fix: calc hit
  src/views/Workshop/Bestiary/CreatureBody.vue
Labels: bug

#142 Fix/tools updates
  src/assets/styles/main.scss
  src/components/content/ContentLayout.vue
  src/views/Inventory/MagicItems/MagicItemLink.vue
  src/views/Tools/EncountersView.vue
  src/views/Tools/MadnessView.vue
  src/views/Tools/TraderView.vue
  src/views/Tools/TreasuryView.vue
  src/views/Tools/WildMagicView.vue
Labels: bug

#152 fix(index.html): update metrics for production
  index.html
Labels: bug

#153 fix(index.html): update metrics for production
  index.html
Labels: bug

#154 fix(ScreensGroup): remove empty group
  src/views/Workshop/Screens/ScreensGroup.vue
Labels: bug

#159 feat: scroll to list item
  src/common/composition/useAppBreakpoints.ts
  src/common/composition/useReference.ts
  src/common/composition/useScrollToPathInList.ts
  src/common/const/UI.ts
  src/common/helpers/dom.ts
  src/components/content/ContentLayout.vue
  src/components/list/VirtualGridList/VirtualGridList.vue
  src/components/list/VirtualGridList/types.ts
  src/components/list/VirtualGroupedList/VirtualGroupedList.vue
  src/components/list/VirtualList/VirtualList.vue
  src/components/list/VirtualList/helpers.ts
  src/components/list/VirtualList/types.ts
  src/views/Character/Backgrounds/BackgroundsView.vue
  src/views/Character/Options/OptionsView.vue
  src/views/Character/Spells/SpellsView.vue
  src/views/Character/Traits/TraitsView.vue
  src/views/Inventory/Armors/ArmorsView.vue
  src/views/Inventory/Items/ItemsView.vue
  src/views/Inventory/MagicItems/MagicItemsView.vue
  src/views/Inventory/Weapons/WeaponsView.vue
  src/views/Wiki/Books/BooksView.vue
  src/views/Wiki/Gods/GodsView.vue
  src/views/Wiki/Rules/RulesView.vue
  src/views/Workshop/Bestiary/BestiaryView.vue
Labels: enhancement

#163 new release (#163)
  src/assets/styles/_theme/theme-dark.scss
  src/assets/styles/_typography.scss
  src/common/composition/useAppBreakpoints.ts
  src/common/composition/useReference.ts
  src/common/composition/useScrollToPathInList.ts
  src/common/const/UI.ts
  src/common/helpers/dom.ts
  src/components/UI/SectionHeader.vue
  src/components/UI/kit/UiInput.vue
  src/components/UI/kit/button/UiButton.vue
  src/components/UI/kit/button/UiEraseButton.vue
  src/components/content/ContentLayout.vue
  src/components/list/VirtualGridList/VirtualGridList.vue
  src/components/list/VirtualGridList/types.ts
  src/components/list/VirtualGroupedList/VirtualGroupedList.vue
  src/components/list/VirtualList/VirtualList.vue
  src/components/list/VirtualList/helpers.ts
  src/components/list/VirtualList/types.ts
  src/types/Shared/Vue.types.ts
  src/views/Character/Backgrounds/BackgroundsView.vue
  src/views/Character/Classes/ClassDetail.vue
  src/views/Character/Options/OptionsView.vue
  src/views/Character/Races/RaceBody.vue
  src/views/Character/Spells/SpellsView.vue
  src/views/Character/Traits/TraitsView.vue
  src/views/Inventory/Armors/ArmorsView.vue
  src/views/Inventory/Items/ItemsView.vue
  src/views/Inventory/MagicItems/MagicItemsView.vue
  src/views/Inventory/Weapons/WeaponsView.vue
  src/views/Wiki/Books/BooksView.vue
  src/views/Wiki/Gods/GodBody.vue
  src/views/Wiki/Gods/GodsView.vue
  src/views/Wiki/Rules/RulesView.vue
  src/views/Workshop/Bestiary/BestiaryView.vue
  src/views/Workshop/Bestiary/CreatureBody.vue
Labels: release
