Repository TTG-Club/ttg-club-frontend, pull requests merged in 2023-05, with the labels that each got.

#70 feat: lazy tippy directive
  src/common/directives/TippyLazy.ts
  src/main.ts
  src/views/Character/Classes/ClassLink.vue
  src/views/Character/Races/RaceLink.vue
  src/views/Character/Spells/SpellLink.vue
  src/views/Inventory/Armors/ArmorLink.vue
  src/views/Inventory/Weapons/WeaponLink.vue
  src/views/Search/SearchLink.vue
  src/views/Wiki/Gods/GodLink.vue
  src/views/Workshop/Screens/ScreenLink.vue
Labels: feature

#65 feat: lists virtualisation
  .eslintrc.js
  package-lock.json
  package.json
  src/assets/styles/_animation.scss
  src/assets/styles/_breakpoints.module.scss
  src/assets/styles/_dependencies.scss
  src/assets/styles/_variables.scss
  src/assets/styles/index.scss
  src/common/composition/useAppBreakpoints.ts
  src/common/composition/useDiceRoller.ts
  src/common/composition/useResponsiveValues.ts
  src/common/const/breakpoints.ts
  src/common/const/index.ts
  src/common/helpers/array.ts
  src/common/helpers/list.ts
  src/components/content/ContentLayout.vue
  src/components/list/GroupedListCategory.vue
  src/components/list/ListRow.vue
  src/components/list/VirtualGridList/VirtualGridList.vue
  src/components/list/VirtualGroupedList/VirtualGroupedList.vue
  src/components/list/VirtualGroupedList/helpers.ts
  src/components/list/VirtualGroupedList/types.ts
  src/components/list/VirtualList.vue
  src/shims-vue.d.ts
  src/types/Shared/Breakpoints.types.ts
  src/types/Shared/List.types.ts
  src/types/Shared/Lodash.types.ts
  src/types/Shared/Utility.types.ts
  src/views/Character/Backgrounds/BackgroundsView.vue
  src/views/Character/Options/OptionsView.vue
  src/views/Character/Spells/SpellsView.vue
  src/views/Character/Traits/TraitsView.vue
  src/views/Inventory/Items/ItemsView.vue
  src/views/Inventory/MagicItems/MagicItemsView.vue
  src/views/Inventory/Treasures/TreasuresView.vue
  src/views/Wiki/Gods/GodsView.vue
  src/views/Wiki/Rules/RulesView.vue
  src/views/Workshop/Bestiary/BestiaryView.vue
  tsconfig.json
Labels: feature

#84 feat(vfm): update vfm library
  package-lock.json
  package.json
  src/App.vue
  src/assets/styles/_dependencies.scss
  src/components/UI/modals/AuthModal.vue
  src/components/UI/modals/BaseModal.vue
  src/components/UI/modals/SearchModal.vue
  src/main.ts
Labels: feature

#88 fix additional speed
  src/views/Workshop/Bestiary/CreatureBody.vue
Labels: bug

#86 works with input
  src/components/UI/icons/SvgIcon.vue
  src/components/UI/kit/UiEraseButton.vue
  src/components/UI/kit/UiInput.vue
  src/components/UI/modals/SearchModal.vue
  src/components/account/ChangePasswordView.vue
  src/components/account/LoginView.vue
  src/components/account/RegistrationView.vue
  src/components/filter/ListFilter.vue
  src/views/Search/SearchView.vue
  src/views/Tools/MadnessView.vue
  src/views/Tools/TraderView.vue
  src/views/Tools/WildMagicView.vue
Labels: feature

#87 feat: added prof bonus
  src/common/composition/useAbilityTransforms.ts
  src/common/composition/usePluralize.ts
  src/common/helpers/abilityTransforms.ts
  src/common/helpers/string.ts
  src/views/Tools/AbilityCalc/AbilityArray.vue
  src/views/Tools/AbilityCalc/AbilityPointBuy.vue
  src/views/Tools/AbilityCalc/AbilityRandom.vue
  src/views/Tools/AbilityCalc/AbilityTable.vue
  src/views/Workshop/Bestiary/CreatureBody.vue
Labels: feature

#79 fix(DetailTooltip): create VNode in detail-tooltip for interactive
  src/components/UI/DetailTooltip.vue
  src/shims-vue.d.ts
Labels: bug

#89 fix(VueFinalModal): closing by button, style .row_info
  src/assets/styles/_dependencies.scss
  src/components/UI/modals/AuthModal.vue
  src/components/UI/modals/BaseModal.vue
Labels: bug

#96 Fix/pre release
  src/assets/icons/svg/theme/light.svg
  src/components/UI/kit/button/UiButton.vue
  src/features/bookmarks/components/buttons/DefaultBookmarkButton.vue
  src/features/bookmarks/store/DefaultBookmarkStore.ts
  src/views/Inventory/MagicItems/MagicItemsView.vue
  src/views/Search/SearchView.vue
Labels: bug

#101 fix: auto open detail
  src/common/helpers/isAutoOpenAvailable.ts
  src/views/Character/Backgrounds/BackgroundsView.vue
  src/views/Character/Options/OptionsView.vue
  src/views/Character/Races/RacesView.vue
  src/views/Character/Spells/SpellsView.vue
  src/views/Character/Traits/TraitsView.vue
  src/views/Inventory/Armors/ArmorsView.vue
  src/views/Inventory/Items/ItemsView.vue
  src/views/Inventory/MagicItems/MagicItemsView.vue
  src/views/Inventory/Weapons/WeaponsView.vue
  src/views/Wiki/Books/BooksView.vue
  src/views/Wiki/Gods/GodsView.vue
  src/views/Wiki/Rules/RulesView.vue
  src/views/Workshop/Bestiary/BestiaryView.vue
  src/views/Workshop/Screens/ScreensView.vue
Labels: bug

#102 hotfix(CreatureBody): remove getFormattedModifier from skills and sav…
  src/views/Workshop/Bestiary/CreatureBody.vue
Labels: bug

#103 Hotfix/proficiency bonus
  src/views/Workshop/Bestiary/CreatureBody.vue
Labels: bug

#105 hotfix(CreatureBody): remove console.log
  src/views/Workshop/Bestiary/CreatureBody.vue
Labels: bug

#104 hotfix(CreatureBody): remove console.log
  src/views/Workshop/Bestiary/CreatureBody.vue
Labels: bug

#107 new release
  src/common/const/index.ts
  src/components/UI/kit/UiSelect.vue
  src/components/content/RawContent.vue
  src/features/bookmarks/components/CustomBookmarks.vue
  src/features/bookmarks/components/CustomBookmarks/CustomBookmarkCategory.vue
  src/views/Character/Classes/ClassDetail.vue
  src/views/Character/Classes/ClassesView.vue
  src/views/Character/Options/OptionsView.vue
  src/views/Character/Spells/SpellsView.vue
  src/views/Tools/TreasuryView.vue
Labels: bug, release

#108 fix: trader-prace
  src/common/services/HTTPService.ts
  src/types/Inventory/MagicItems.types.ts
  src/types/Shared/BaseApiFields.types.ts
  src/types/Tools/Trader.types.ts
  src/views/Inventory/MagicItems/MagicItemLink.vue
  src/views/Tools/TraderView.vue
Labels: feature

#97 feat: vite builder
  .env
  .env.development
  .env.example
  .env.production
  .eslintrc.js
  .github/workflows/build.yml
  .github/workflows/lint-pr.yml
  .github/workflows/lint.yml
  .gitignore
  .husky/pre-commit
  index.html
  jsconfig.json
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/common/helpers/isDev.ts
  src/common/services/HTTPService.ts
  src/common/utils/SvgRequire.ts
  src/components/UI/icons/SvgIcon.vue
  src/components/UI/kit/button/UiEraseButton.vue
  src/components/UI/modals/SearchModal.vue
  src/components/content/PageLayout.vue
  src/components/list/VirtualGridList/VirtualGridList.vue
  src/components/list/VirtualGroupedList/VirtualGroupedList.vue
  src/components/list/VirtualList/VirtualList.vue
  src/main.ts
  src/router/routes.ts
  src/shims-vue.d.ts
  src/views/Character/Backgrounds/BackgroundsView.vue
  src/views/Character/Options/OptionsView.vue
  src/views/Character/Spells/SpellsView.vue
  src/views/Character/Traits/TraitsView.vue
  src/views/Inventory/Armors/ArmorsView.vue
  src/views/Inventory/Items/ItemsView.vue
  src/views/Inventory/MagicItems/MagicItemsView.vue
  src/views/Inventory/Treasures/TreasuresView.vue
  src/views/Inventory/Weapons/WeaponsView.vue
  src/views/Wiki/Gods/GodsView.vue
  src/views/Wiki/Rules/RulesView.vue
  src/views/Workshop/Bestiary/BestiaryView.vue
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
  vue.config.js
Labels: feature

#139 fix: in tab list grid
  src/assets/styles/modules/link-item.scss
  src/components/list/VirtualGridList/helpers.ts
  src/views/Character/Options/OptionLink.vue
  src/views/Character/Options/OptionsView.vue
  src/views/Character/Spells/SpellLink.vue
  src/views/Character/Spells/SpellsView.vue
Labels: bug
