Repository TTG-Club/ttg-club-frontend, pull requests merged in 2024-04, with the labels that each got.

#262 Экспорт для LSS
  src/features/SectionHeader.vue
  src/pages/character/spells/spells-detail/SpellDetail.vue
  src/pages/workshop/bestiary/creature-detail/CreatureDetail.vue
  src/shared/api/httpClient.ts
  src/shared/types/BaseApiFields.d.ts
  src/shared/ui/ContentDetail.vue
  src/shared/ui/DetailTooltip.vue
  src/shared/utils/exportDetail.ts
  src/shared/utils/getApiUrl.ts
Labels: улучшение

#264 Update width menu
  src/assets/styles/modules/navbar.scss
  src/features/menu/NavBar.vue
  src/layouts/ContentLayout.vue
Labels: улучшение

#265 new release
  .eslintrc.cjs
  public/img/bg_discord_bot.webp
  public/img/bg_main_page_button_nav.webp
  public/img/bg_main_page_button_nav_3.png
  public/img/bg_main_page_button_nav_mobile_3.png
  public/img/bg_telegram_bot.webp
  public/img/bg_token_library.webp
  src/assets/styles/_typography.scss
  src/assets/styles/base.scss
  src/assets/styles/main.scss
  src/assets/styles/modules/navbar.scss
  src/assets/styles/variables/colors.scss
  src/features/DetailTopBar.vue
  src/features/MenuThemeSwitcher.vue
  src/features/SectionHeader.vue
  src/features/menu/NavBar.vue
  src/features/menu/NavMenu.vue
  src/features/menu/NavPopover.vue
  src/features/menu/NavProfile.vue
  src/layouts/ContentLayout.vue
  src/pages/character/feats/FeatLink.vue
  src/pages/character/feats/FeatsView.vue
  src/pages/character/feats/feats-detail/FeatBody.vue
  src/pages/character/feats/feats-detail/FeatDetail.vue
  src/pages/character/feats/feats-detail/index.ts
  src/pages/character/feats/index.ts
  src/pages/character/index.ts
  src/pages/character/spells/spells-detail/SpellDetail.vue
  src/pages/character/traits/index.ts
  src/pages/character/traits/traits-detail/TraitBody.vue
  src/pages/character/traits/traits-detail/TraitDetail.vue
  src/pages/character/traits/traits-detail/index.ts
  src/pages/index.ts
  src/pages/inventory/magic-items/MagicItemLink.vue
  src/pages/workshop/bestiary/creature-detail/CreatureDetail.vue
  src/shared/api/httpClient.ts
  src/shared/composables/usePagination.ts
  src/shared/types/BaseApiFields.d.ts
  src/shared/types/character/Feats.d.ts
  src/shared/types/character/Traits.d.ts
  src/shared/ui/ContentDetail.vue
  src/shared/ui/DetailTooltip.vue
  src/shared/ui/DiceRoller.vue
  src/shared/ui/icons/SiteLogo.vue
  src/shared/utils/exportDetail.ts
  src/shared/utils/getApiUrl.ts
  src/shared/utils/isAutoOpenAvailable.ts
Labels: release

#266 hotfix: export detail
  src/shared/utils/exportDetail.ts
Labels: bug

#254 История бросков
  package-lock.json
  package.json
  src/assets/styles/modules/navbar.scss
  src/core/App.vue
  src/core/router.ts
  src/features/dice-history/composables/index.ts
  src/features/dice-history/composables/useDiceHistory.ts
  src/features/dice-history/ui/ClearButton.vue
  src/features/dice-history/ui/DiceHistory.vue
  src/features/dice-history/ui/DiceHistoryInput.vue
  src/features/dice-history/ui/DiceHistoryItem.vue
  src/features/dice-history/ui/DiceHistoryWindowContent.vue
  src/features/dice-history/ui/index.ts
  src/features/dice-notification/index.ts
  src/features/dice-notification/useDiceNotification.ts
  src/features/menu/NavBar.vue
  src/features/menu/NavDiceHistoryButton.vue
  src/pages/character/backgrounds/backgrounds-detail/BackgroundDetail.vue
  src/pages/character/classes/classes-detail/ClassDetail.vue
  src/pages/character/feats/feats-detail/FeatDetail.vue
  src/pages/character/options/options-detail/OptionDetail.vue
  src/pages/character/races/races-detail/RaceDetail.vue
  src/pages/character/spells/spells-detail/SpellDetail.vue
  src/pages/inventory/armors/armors-detail/ArmorDetail.vue
  src/pages/inventory/items/items-detail/ItemDetail.vue
  src/pages/inventory/magic-items/magic-items-detail/MagicItemDetail.vue
  src/pages/inventory/weapons/weapons-detail/WeaponBody.vue
  src/pages/inventory/weapons/weapons-detail/WeaponDetail.vue
  src/pages/tools/ability-calc/AbilityCalcView.vue
  src/pages/workshop/bestiary/creature-detail/CreatureDetail.vue
  src/pages/workshop/screens/screens-detail/ScreenDetail.vue
  src/shared/composables/useClassName.ts
  src/shared/composables/useDiceRoller.ts
  src/shared/composables/useLocalforageItem.ts
  src/shared/stores/RollStore.ts
  src/shared/ui/BottomRightWindow.vue
  src/shared/ui/ContentDetail.vue
  src/shared/ui/DiceRoller.vue
  src/shared/ui/kit/button/UiButton.vue
  src/shared/ui/kit/button/UiFab.vue
  src/shared/utils/className.ts
  src/shared/utils/eventBus.ts
  src/shared/utils/roll.ts
  src/shared/utils/types.ts
Labels: фича
